"""Milestone 10: typing lane (ACTIVE + PASSIVE).

PRIVACY -- read this before touching the keystroke capture code below.
This module retains keystroke TIMING ONLY: inter-key intervals, key-down/
key-up perf_counter() timestamps, and a per-character boolean
matched_expected (ACTIVE mode -- did this keystroke match the next
expected character of the session's challenge phrase?). It NEVER stores,
logs, returns, or serialises the pressed character, the phrase as actually
typed, clipboard content, or window titles. The pressed character exists
only as a local variable inside KeystrokeCapture._on_press, used for a
single equality comparison against the expected phrase, and goes out of
scope the instant that function returns -- it is never appended to
KeystrokeCapture.events or any other structure that outlives the callback.
This is the single line between this project and a keylogger, and it is a
claim made in the patent disclosure. Do not weaken it: if you find yourself
wanting to store, print, or return the character for debugging, don't --
matched_expected (a boolean) is the only signal this module is allowed to
carry about WHAT was typed.

ACTIVE mode displays a session-unique challenge phrase (generated by
praesens.challenge.generate_challenge_phrase) and verifies keystrokes
against it, plus checks keystroke timing against camera-observed hand
motion. PASSIVE mode drops the phrase entirely and checks ONLY keystroke-
hand coherence on whatever the operator naturally types -- there is no
expected sequence to compare against, so matched_expected is always None
in PASSIVE mode. Confidence decays with time since the last keystroke;
sustained silence triggers a re-challenge rather than silently degrading
to a stale verdict.

Hand-motion coherence uses MediaPipe's HandLandmarker on the SAME camera
stream the optical lane already has open -- callers integrating this lane
must feed frames in rather than opening a second cv2.VideoCapture, since
opening two capture handles to one physical camera is unreliable at best
on most drivers (see also demo/attack.py's own reasoning for pre-opening
capture handles instead of reopening them).
"""
from __future__ import annotations

import math
import threading
import time
from collections import Counter, deque
from dataclasses import dataclass, field
from pathlib import Path

import cv2
import mediapipe as mp
import numpy as np
from pynput import keyboard

from mediapipe.tasks.python import vision as mp_vision
from mediapipe.tasks.python import BaseOptions


# ---------------------------------------------------------------------------
# Keystroke timing capture -- see module docstring for the privacy contract.
# ---------------------------------------------------------------------------

class KeystrokeCapture:
    """expected_phrase=None runs in PASSIVE mode: no cursor, no matching,
    matched_expected is always None. expected_phrase=<str> runs ACTIVE:
    each printable keypress is compared against the next expected
    character (only the BOOLEAN result is kept, see module docstring)."""

    def __init__(self, expected_phrase: str | None = None):
        self.expected_phrase = expected_phrase
        self._cursor = 0
        self.events: list[dict] = []  # {"t_down","t_up","matched_expected"} ONLY -- no characters, ever
        self._open_indices: deque = deque()
        self._lock = threading.Lock()
        self._listener: keyboard.Listener | None = None

    @property
    def phrase_complete(self) -> bool:
        return self.expected_phrase is not None and self._cursor >= len(self.expected_phrase)

    @property
    def chars_matched(self) -> int:
        """How many characters of expected_phrase have been correctly
        typed IN ORDER so far -- a COUNT only, consistent with this
        module's privacy contract (never which characters, never the
        phrase as actually typed). Lets a caller (e.g. an on-screen
        prompt) show live progress against the ALREADY-KNOWN, already-
        displayed expected phrase without learning anything about what
        was actually pressed beyond this running count."""
        return self._cursor

    @staticmethod
    def _extract_char_local(key):
        """Local-scope-only: the return value is used for ONE comparison
        by the caller and must never be stored, logged, or returned
        further up the call stack (see module docstring)."""
        if key == keyboard.Key.space:
            return " "
        return getattr(key, "char", None)

    def _on_press(self, key) -> None:
        t = time.perf_counter()
        pressed_char = self._extract_char_local(key)  # local only
        matched = None
        if self.expected_phrase is not None and pressed_char is not None and not self.phrase_complete:
            expected_char = self.expected_phrase[self._cursor]
            matched = (pressed_char == expected_char)
            if matched:
                self._cursor += 1
        with self._lock:
            self.events.append({"t_down": t, "t_up": None, "matched_expected": matched})
            self._open_indices.append(len(self.events) - 1)
        # pressed_char and key fall out of scope here; nothing further
        # references either, so no persisted structure ever holds them.

    def _on_release(self, key) -> None:
        t = time.perf_counter()
        with self._lock:
            if self._open_indices:
                idx = self._open_indices.popleft()  # FIFO pairing, approximate but privacy-safe
                self.events[idx]["t_up"] = t

    def start(self) -> None:
        self._listener = keyboard.Listener(on_press=self._on_press, on_release=self._on_release)
        self._listener.start()

    def stop(self) -> None:
        if self._listener is not None:
            self._listener.stop()
            self._listener = None

    def get_events(self) -> list[dict]:
        with self._lock:
            return [dict(e) for e in self.events]

    def last_keystroke_time(self) -> float | None:
        events = self.get_events()
        return max((e["t_down"] for e in events), default=None)

    def inter_key_intervals(self) -> np.ndarray:
        events = self.get_events()
        if len(events) < 2:
            return np.array([])
        t_downs = np.array([e["t_down"] for e in events])
        return np.diff(t_downs)


# ---------------------------------------------------------------------------
# Hand-motion coherence
# ---------------------------------------------------------------------------

def _derive_fingertip_index(connections_finger, connections_palm) -> int:
    """Same technique as praesens/optical.py's ROI derivation: pull the
    index from MediaPipe's own connection sets rather than a memorised
    landmark number. A finger's connection chain has exactly two degree-1
    nodes -- the base (MCP, which also appears in the palm connections)
    and the tip (which appears nowhere else). The one NOT in the palm set
    is the tip."""
    deg = Counter()
    for c in connections_finger:
        deg[c.start] += 1
        deg[c.end] += 1
    degree_one = [n for n, d in deg.items() if d == 1]
    palm_nodes = set()
    for c in connections_palm:
        palm_nodes.add(c.start)
        palm_nodes.add(c.end)
    tip_candidates = [n for n in degree_one if n not in palm_nodes]
    if len(tip_candidates) != 1:
        raise ValueError(f"expected exactly one fingertip candidate, got {tip_candidates}")
    return tip_candidates[0]


_HLC = mp_vision.HandLandmarksConnections
INDEX_FINGERTIP_IDX = _derive_fingertip_index(_HLC.HAND_INDEX_FINGER_CONNECTIONS, _HLC.HAND_PALM_CONNECTIONS)


def create_hand_landmarker(model_path: str, running_mode=mp_vision.RunningMode.VIDEO,
                            min_confidence: float = 0.5):
    model_path = Path(model_path)
    if not model_path.exists():
        raise FileNotFoundError(
            f"HandLandmarker model not found at {model_path}. Run "
            f"'python scripts/fetch_model.py --hand' once to download it."
        )
    options = mp_vision.HandLandmarkerOptions(
        base_options=BaseOptions(model_asset_path=str(model_path)),
        running_mode=running_mode,
        num_hands=2,
        min_hand_detection_confidence=min_confidence,
        min_hand_presence_confidence=min_confidence,
        min_tracking_confidence=min_confidence,
    )
    return mp_vision.HandLandmarker.create_from_options(options)


class HandActivityTracker:
    """Turns HandLandmarker results into a scalar "how much is the hand
    moving right now" signal: index-fingertip displacement magnitude from
    the previous DETECTED frame, summed over however many hands are
    visible. Genuine typing produces bursts of this signal roughly
    synchronised with keystrokes; an injected video's hands (if visible at
    all) move on their own unrelated schedule."""

    def __init__(self):
        self._last_positions: dict[int, np.ndarray] = {}

    def process(self, result) -> float:
        """NaN if no hand detected this frame -- caller should treat a
        session with too few non-NaN samples as no_evidence, not score it
        as zero (rule 7: a lane that can't produce evidence says so)."""
        if not result.hand_landmarks:
            self._last_positions = {}
            return float("nan")
        total = 0.0
        n = 0
        new_positions = {}
        for i, hand in enumerate(result.hand_landmarks):
            tip = hand[INDEX_FINGERTIP_IDX]
            pos = np.array([tip.x, tip.y])
            new_positions[i] = pos
            if i in self._last_positions:
                total += float(np.linalg.norm(pos - self._last_positions[i]))
                n += 1
        self._last_positions = new_positions
        return total if n > 0 else 0.0

    def reset(self) -> None:
        self._last_positions = {}


def keystroke_impulse_density(events: list, query_timestamps: np.ndarray, sigma_s: float) -> np.ndarray:
    """Smooth keystroke "density" at arbitrary query times: sum of
    Gaussian kernels centred on each keystroke's t_down. Turns a sparse
    impulse train into something correlatable against a continuous
    (irregularly-sampled) hand-activity signal."""
    query_timestamps = np.asarray(query_timestamps, dtype=np.float64)
    if not events:
        return np.zeros(len(query_timestamps))
    t_downs = np.array([e["t_down"] for e in events])
    out = np.zeros(len(query_timestamps))
    for t0 in t_downs:
        out += np.exp(-0.5 * ((query_timestamps - t0) / sigma_s) ** 2)
    return out


def keystroke_hand_coherence(events: list, hand_ts: np.ndarray, hand_activity: np.ndarray,
                              sigma_s: float, lag_max_ms: float, lag_step_ms: float,
                              min_valid_samples: int = 5) -> tuple:
    """Cross-correlates keystroke density against hand activity over a lag
    grid bounded on BOTH sides of zero -- unlike the optical lane's
    0-to-300ms-only search, finger motion and key-down registration are
    both downstream of the same physical press (the motion IS what causes
    the contact), not a one-directional stimulus-then-response
    relationship like light reflection, so the measured velocity peak
    could fall slightly before OR after the electrical key-down event.
    Returns (score, lag_ms), or (nan, nan) if there isn't enough valid
    data -- caller maps that to no_evidence, never to a zero score."""
    hand_ts = np.asarray(hand_ts, dtype=np.float64)
    hand_activity = np.asarray(hand_activity, dtype=np.float64)
    valid = ~np.isnan(hand_activity)
    ts = hand_ts[valid]
    activity = hand_activity[valid]
    if len(activity) < min_valid_samples or np.std(activity) < 1e-9 or not events:
        return float("nan"), float("nan")

    a_centered = activity - activity.mean()
    a_std = np.std(a_centered)

    lags_ms = np.arange(-lag_max_ms, lag_max_ms + 1e-9, lag_step_ms)
    best_score, best_lag = -np.inf, 0.0
    for lag_ms in lags_ms:
        density = keystroke_impulse_density(events, ts - lag_ms / 1000.0, sigma_s)
        d_centered = density - density.mean()
        d_std = np.std(d_centered)
        corr = 0.0 if d_std < 1e-9 else float(np.mean(a_centered * d_centered) / (a_std * d_std))
        if corr > best_score:
            best_score, best_lag = corr, float(lag_ms)
    return best_score, best_lag


# ---------------------------------------------------------------------------
# Passive-mode confidence decay
# ---------------------------------------------------------------------------

def compute_typing_status(mode: str, silence_s: float, n_hand_valid: int,
                           min_valid_hand_samples: int, passive_no_evidence_after_s: float,
                           n_events: int) -> str:
    """The no_evidence decision, isolated from run_typing_session's camera/
    keyboard I/O so "operator stops typing for N seconds -> no_evidence"
    can be tested deterministically without hardware. PASSIVE mode has no
    expected sequence to complete, so its no_evidence trigger is sustained
    silence (including "never typed at all," silence_s=inf) rather than
    "zero keystrokes across the whole window" -- someone who typed early
    and then stopped should read as no_evidence by the end, not "ok"
    because SOME typing happened earlier in the window."""
    no_hand_evidence = n_hand_valid < min_valid_hand_samples
    if mode == "passive":
        no_typing_recently = silence_s >= passive_no_evidence_after_s
    else:
        no_typing_recently = n_events == 0
    return "no_evidence" if (no_typing_recently or no_hand_evidence) else "ok"


def passive_confidence(last_keystroke_time: float | None, now: float, decay_half_life_s: float) -> float:
    """1.0 right after a keystroke, halving every decay_half_life_s
    seconds of silence. No keystrokes at all yet -> 0.0. Caller triggers a
    re-challenge once this drops below a configured floor."""
    if last_keystroke_time is None:
        return 0.0
    dt = max(0.0, now - last_keystroke_time)
    return float(2 ** (-dt / decay_half_life_s))


# ---------------------------------------------------------------------------
# Keystroke-TIMING-ONLY scoring (2026-09-03) -- no camera/hand-tracking
# dependency at all. Added because keystroke_hand_coherence() above,
# while real and tested, requires the camera to see BOTH the face (for
# the optical lane) and the hands (for this one) at once -- not physically
# realistic for a webcam framed on the face during normal typing, which
# made this lane read as no_evidence in practice regardless of whether
# genuine typing happened. This scores two things instead, both derivable
# from keystroke timing alone: did the operator correctly type THIS
# SESSION'S freshly-generated, unpredictable phrase (proves live
# engagement with a challenge that couldn't have been pre-recorded), and
# was the keystroke rhythm within a plausible human range (catches a
# naive scripted/replayed keystroke injection, which types with
# unnaturally uniform, fast timing). Still keystroke-TIMING only, per the
# module's privacy contract -- events already never carry characters.
# ---------------------------------------------------------------------------

def keystroke_normality_score(events: list, expected_phrase: str | None, config: "TypingConfig") -> tuple:
    """Returns (status, subscore, diagnostics). status is "ok" or
    "no_evidence" (never "insufficient_signal" -- that status belongs to
    optical's SNR concept, not applicable here). subscore is None unless
    status=="ok", matching LaneResult's own contract."""
    if len(events) < config.min_keystrokes:
        return "no_evidence", None, f"n_keystrokes={len(events)} (need >= {config.min_keystrokes})"

    n_matched = sum(1 for e in events if e["matched_expected"] is True)
    n_expected = len(expected_phrase) if expected_phrase else len(events)
    match_fraction = (n_matched / n_expected) if n_expected else 0.0

    t_downs = sorted(e["t_down"] for e in events)
    intervals = [b - a for a, b in zip(t_downs, t_downs[1:])]
    mean_interval = (sum(intervals) / len(intervals)) if intervals else float("nan")

    timing_plausible = (not math.isnan(mean_interval)
                         and config.min_inter_key_s <= mean_interval <= config.max_inter_key_s)

    subscore = match_fraction if timing_plausible else match_fraction * config.implausible_timing_penalty

    interval_str = f"{mean_interval:.3f}s" if not math.isnan(mean_interval) else "n/a"
    diagnostics = f"matched {n_matched}/{n_expected}, mean_inter_key={interval_str}"
    if not timing_plausible:
        diagnostics += " (timing outside plausible human range)"
    return "ok", float(subscore), diagnostics


# ---------------------------------------------------------------------------
# Config + standalone session runner
# ---------------------------------------------------------------------------

@dataclass
class TypingConfig:
    n_words: int = 5
    hand_model_path: str = "models/hand_landmarker.task"
    min_hand_confidence: float = 0.5
    coherence_sigma_s: float = 0.15
    coherence_lag_max_ms: float = 300.0
    coherence_lag_step_ms: float = 10.0
    min_valid_hand_samples: int = 5
    passive_decay_half_life_s: float = 5.0
    passive_no_evidence_after_s: float = 10.0
    camera_index: int = 0
    # -- 2026-09-03: keystroke-timing-only scoring, see keystroke_normality_score()
    min_keystrokes: int = 3
    min_inter_key_s: float = 0.03
    max_inter_key_s: float = 3.0
    implausible_timing_penalty: float = 0.3
    pass_match_fraction: float = 0.7

    @classmethod
    def from_dict(cls, d: dict) -> "TypingConfig":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class TypingResult:
    mode: str  # "active" or "passive"
    status: str  # "ok" | "no_evidence"
    n_keystrokes: int
    n_matched: int | None  # ACTIVE only
    n_expected: int | None  # ACTIVE only, len(phrase)
    inter_key_mean_s: float
    inter_key_std_s: float
    coherence_score: float  # nan if no_evidence
    coherence_lag_ms: float  # nan if no_evidence
    seconds_since_last_keystroke: float  # inf if no keystrokes at all this session
    events: list  # {"t_down","t_up","matched_expected"} -- no characters


class TypingFrameProcessor:
    """Per-frame hand-tracking state, extracted (2026-09-02) from
    run_typing_session()'s inline loop body so a caller driving its OWN
    shared frame loop -- e.g. praesens/session.py's concurrent optical+
    typing path, where one grab/retrieve loop must feed the SAME frame to
    both lanes -- can feed frames in one at a time instead of this module
    owning cap.grab()/retrieve() itself. The keystroke listener thread
    (KeystrokeCapture) is untouched by this: it never read from the
    camera and needs no change; only hand-tracking (which DOES need
    frames) is extracted here. Every line of computation below is
    verbatim from the pre-refactor run_typing_session() loop body."""

    def __init__(self, landmarker):
        self.landmarker = landmarker  # lifecycle owned by the CALLER (own_landmarker stays their concern)
        self.tracker = HandActivityTracker()
        self.hand_ts: list = []
        self.hand_activity: list = []
        self._last_ts_ms = -1

    def process_frame(self, frame, t: float, start_time: float) -> None:
        ts_ms = max(self._last_ts_ms + 1, int((t - start_time) * 1000))
        self._last_ts_ms = ts_ms

        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
        result = self.landmarker.detect_for_video(mp_image, ts_ms)
        activity = self.tracker.process(result)

        self.hand_ts.append(t)
        self.hand_activity.append(activity)


def finalize_typing_result(capture: KeystrokeCapture, hand_ts: list, hand_activity: list,
                            mode: str, config: TypingConfig, start_time: float, duration_s: float,
                            expected_phrase: str | None) -> TypingResult:
    """The post-loop tail of the pre-refactor run_typing_session(),
    verbatim -- turns accumulated keystroke events + a hand-activity trace
    into a TypingResult. Caller must have already called capture.stop();
    this function only reads from capture, it doesn't manage its
    lifecycle (mirrors OpticalFrameProcessor.finalize()'s split of
    "own the loop" vs. "compute the result" in praesens/optical.py)."""
    events = capture.get_events()
    intervals = capture.inter_key_intervals()

    session_end = start_time + duration_s
    last_kt = capture.last_keystroke_time()
    silence_s = (session_end - last_kt) if last_kt is not None else float("inf")

    n_hand_valid = int(np.sum(~np.isnan(hand_activity))) if hand_activity else 0
    status = compute_typing_status(mode, silence_s, n_hand_valid, config.min_valid_hand_samples,
                                    config.passive_no_evidence_after_s, len(events))

    if status == "ok":
        coherence_score, coherence_lag = keystroke_hand_coherence(
            events, np.array(hand_ts), np.array(hand_activity),
            config.coherence_sigma_s, config.coherence_lag_max_ms, config.coherence_lag_step_ms,
            config.min_valid_hand_samples,
        )
    else:
        coherence_score, coherence_lag = float("nan"), float("nan")

    n_matched = sum(1 for e in events if e["matched_expected"] is True) if mode == "active" else None
    n_expected = len(expected_phrase) if mode == "active" and expected_phrase else None

    return TypingResult(
        mode=mode, status=status, n_keystrokes=len(events),
        n_matched=n_matched, n_expected=n_expected,
        inter_key_mean_s=float(np.mean(intervals)) if len(intervals) else float("nan"),
        inter_key_std_s=float(np.std(intervals)) if len(intervals) else float("nan"),
        coherence_score=coherence_score, coherence_lag_ms=coherence_lag,
        seconds_since_last_keystroke=silence_s,
        events=events,
    )


def run_typing_session(mode: str, duration_s: float, config: TypingConfig, cap,
                        landmarker=None, expected_phrase: str | None = None) -> TypingResult:
    """Runs one ACTIVE or PASSIVE typing-lane session against an ALREADY-
    OPEN cv2.VideoCapture (never opens its own -- see module docstring).
    ACTIVE requires expected_phrase; PASSIVE ignores it. Thin wrapper
    around TypingFrameProcessor (see its docstring) -- owns its own grab/
    retrieve loop for callers that only need the typing lane; the
    concurrent optical+typing path in praesens/session.py drives
    TypingFrameProcessor directly instead, from its own shared loop."""
    if mode not in ("active", "passive"):
        raise ValueError(f"mode must be 'active' or 'passive', got {mode!r}")
    if mode == "active" and not expected_phrase:
        raise ValueError("active mode requires expected_phrase")

    own_landmarker = landmarker is None
    if own_landmarker:
        landmarker = create_hand_landmarker(config.hand_model_path, mp_vision.RunningMode.VIDEO,
                                             config.min_hand_confidence)

    capture = KeystrokeCapture(expected_phrase=expected_phrase if mode == "active" else None)
    capture.start()

    processor = TypingFrameProcessor(landmarker)
    start_time = time.perf_counter()

    try:
        while True:
            elapsed = time.perf_counter() - start_time
            if elapsed >= duration_s:
                break
            if mode == "active" and capture.phrase_complete:
                break

            grabbed = cap.grab()
            t = time.perf_counter()
            if not grabbed:
                continue
            ok, frame = cap.retrieve()
            if not ok or frame is None:
                continue

            processor.process_frame(frame, t, start_time)
    finally:
        capture.stop()
        if own_landmarker:
            landmarker.close()

    return finalize_typing_result(capture, processor.hand_ts, processor.hand_activity,
                                   mode, config, start_time, duration_s, expected_phrase)


if __name__ == "__main__":
    import argparse
    import json
    import yaml

    from praesens.challenge import generate_challenge_phrase

    parser = argparse.ArgumentParser(description="Milestone 10 typing lane smoke test")
    parser.add_argument("--mode", choices=["active", "passive"], default="active")
    parser.add_argument("--seconds", type=float, default=30.0)
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    with open(repo_root / "config.yaml") as f:
        raw = yaml.safe_load(f)

    tconfig = TypingConfig.from_dict(raw.get("typing", {}))
    tconfig.hand_model_path = str(repo_root / tconfig.hand_model_path)

    from praesens.camera import open_camera
    from praesens.capture import CaptureConfig, configure_capture_format
    cap = open_camera(tconfig.camera_index)
    if not cap.isOpened():
        raise RuntimeError(f"could not open camera index {tconfig.camera_index}")
    cconfig = CaptureConfig.from_dict(raw.get("capture", {}))
    configure_capture_format(cap, cconfig)  # no exposure lock here, matching this lane's existing behaviour

    phrase = None
    if args.mode == "active":
        seed = args.seed if args.seed is not None else int(np.random.default_rng().integers(1, 1_000_000))
        phrase = generate_challenge_phrase(seed, n_words=tconfig.n_words,
                                            generative=raw.get("typing", {}).get("generative", False))
        print(f"\n{'=' * 60}\nTYPE THIS PHRASE:\n\n  {phrase}\n{'=' * 60}\n")
        print("(the pressed characters are never logged -- only whether each one "
              "matched, see this module's docstring)")
    else:
        print(f"\nPASSIVE mode: type naturally for up to {args.seconds:.0f}s, no phrase shown.\n")

    result = run_typing_session(args.mode, args.seconds, tconfig, cap, expected_phrase=phrase)
    cap.release()

    print(f"\nstatus={result.status}  n_keystrokes={result.n_keystrokes}")
    if result.mode == "active":
        print(f"matched {result.n_matched}/{result.n_expected} expected characters")
    print(f"inter_key_mean_s={result.inter_key_mean_s:.3f}  inter_key_std_s={result.inter_key_std_s:.3f}")
    print(f"coherence_score={result.coherence_score:.3f}  coherence_lag_ms={result.coherence_lag_ms:.1f}")
    print(f"seconds_since_last_keystroke={result.seconds_since_last_keystroke:.1f}")

    out_path = repo_root / "logs" / f"typing_{int(time.time())}.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump({
            "mode": result.mode, "status": result.status,
            "n_keystrokes": result.n_keystrokes, "n_matched": result.n_matched,
            "n_expected": result.n_expected,
            "inter_key_mean_s": result.inter_key_mean_s, "inter_key_std_s": result.inter_key_std_s,
            "seconds_since_last_keystroke": result.seconds_since_last_keystroke,
            "coherence_score": result.coherence_score, "coherence_lag_ms": result.coherence_lag_ms,
            "events": result.events,  # t_down/t_up/matched_expected ONLY -- see module docstring
        }, f, indent=2)
    print(f"saved to {out_path}")
